### PR TITLE
Update jQuery.param.xml

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixed issue #598.

### CODE REVIEW

**Comment by dmethvin** [comment]
Perfect.

**Comment by arthurvr** [comment]
LGTM. I can merge if nobody disagrees.

**Comment by kswedberg** [comment]
Go for it!

**Comment by arthurvr** [comment]
Merged! Thanks @AurelioDeRosa!

**Comment by AurelioDeRosa** [comment]
Glad to help @arthurvr :)

**Pull request closed without merging**
