### PR TITLE
categories: Add the 3.0 section

### LINKED ISSUE #937: master is broken
After merging the `v3.0.0-docs` branch to `master` the build is broken. The `version/3.0` slug is missing so `grunt deploy` ends with:
```
Error: post jQuery.escapeSelector has a category term slug of 'version/3.0', but no such term exists.
```

### PR DESCRIPTION
**Pull request by mgol**
The docs don't build without this PR so I'd like to land it quickly.

Fixes #937

Is the message right? @jquery/core

### CODE REVIEW

**Comment by timmywil** [comment]
That seems right, but perhaps @AurelioDeRosa or @arthurvr could confirm.

**Comment by mgol** [comment]
I confirmed it works locally. Before this PR I was getting the error described in #937, after applying it everything built & e.g. https://api.jquery.com/jQuery.escapeSelector/ displays fine whereas now it's a 404.

**Comment by mgol** [comment]
I'm going on vacation tomorrow (I'll be back on Thursday) so if no one opposes I'd like to land it later today.

**Comment by AurelioDeRosa** [comment]
LGTM

**Pull request closed without merging**
