### PR TITLE
change http to https where applicable

### PR DESCRIPTION
**Pull request by OmgImAlexis**
I noticed that `http://jquery14.com` doesn't exist anymore and html5shiv now points to Github instead of Google code.

I'm not sure what to change `http://jquery14.com` to.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
I already signed this with `X O` being my full name and `xo@wvvw.me` being my email address.

**Comment by OmgImAlexis** [comment]
@AurelioDeRosa I'm hoping you could help, the CLA bot doesn't seem to want to accept me. I've signed it 5 times now using `X O` for the name and `xo@wvvw.me` for the email.

**Comment by dmethvin** [comment]
Ok, the CLA issue should be fixed now. For now I guess we just leave those jquery14.com links as-is but we should try to find that content and put it up somewhere (maybe just retroactively edit [this blog post](https://blog.jquery.com/2010/01/14/jquery-14-released/)). @s5fs do we have a copy archived?

**Comment by OmgImAlexis** [comment]
:+1: Sounds good. I would have changed it myself but I wasn't sure what that domain was meant to go to in the first place.

**Comment by scottgonzalez** [comment]
All of the jquery14.com videos are published on https://m.youtube.com/#/playlist?list=PL-0yjdC10QYqVoqZQ6gc_y7_W401eVLaZ

**Comment by dmethvin** [comment]
I was mostly looking for the release notes, it's one of the few where they aren't in the blog. The [blog post](https://blog.jquery.com/2010/01/14/jquery-14-released/)just links to jquery14.com.

**Comment by dmethvin** [comment]
Ah found it at archive.org. I'll make a ticket.

**Comment by OmgImAlexis** [comment]
@dmethvin since I plan on updating every single site in the jQuery organisation like I have with this would it be okay to ping you on each PR to get them moving along quicker?

**Comment by dmethvin** [comment]
I'm already notified on many of the repos. If something doesn't get attention after a week, ping me then.

**Comment by OmgImAlexis** [comment]
Sure thing. :+1:

**Pull request closed without merging**
