### PR TITLE
toggleClass: Document deprecation of a signature

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-851

### CODE REVIEW

**Comment by dmethvin** [comment]
Not sure how we want to document this, but the signature is actually removed as of 3.0. Perhaps we document it as deprecated as of 1.12.0?

**Comment by timmywil** [comment]
That's one way to go, but I figured we'd remove it in 4.0 https://github.com/jquery/api.jquery.com/issues/851#issuecomment-169804944.

**Comment by AurelioDeRosa** [comment]
Is it good to merge?

**Comment by timmywil** [comment]
It looks ok to me, but the build is failing.

**Comment by AurelioDeRosa** [comment]
We have the usual issue that branch 3 doesn't have the Travis file, thus it fails.

**Pull request closed without merging**
