### PR TITLE
jQuery.uniqueSort: Fixed category name

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-908

### CODE REVIEW

**Comment by dmethvin** [comment]
Ah, so the encoded version works? Awesome!

**Comment by AurelioDeRosa** [comment]
@agcolom did you have the chance to double-check this?

**Comment by agcolom** [comment]
@AurelioDeRosa My local setup is no longer working for the core api (not sure what change broke it yet, and I cannot install anything as I get the error on npm install!) so I haven't been able to test this, sorry.

**Comment by kswedberg** [comment]
@AurelioDeRosa this needs a corresponding `<category>` entry in the categories.xml file. Unfortunately, when I try to add `<category name="Version 1.12&amp;2.2" slug="1.12&amp;2.2">…</category>`, I get "Warning: Invalid slug: 1.12&2.2." Using a hyphen (-) works. Maybe we should use that instead?

**Comment by kswedberg** [comment]
@AurelioDeRosa ugh, I think I spoke too soon. While I don't get the error when I use `<category name="Version 1.12-2.2" slug="1.12-2.2">` (hyphens). The build process seems to ignore it. Maybe there's a stricter check when adding the version than when validating it?

**Comment by AurelioDeRosa** [comment]
@kswedberg I managed to have the dash working. I think what was wrong is that `$.uniqueSort()` doesn't not include the category at the bottom of the file.

If everyone is happy, I can update the PR and merge it.

**Comment by kswedberg** [comment]
Aha! You're correct, @AurelioDeRosa . That was the missing piece of the puzzle. Thanks so much for looking into this. Please update and merge.

**Comment by AurelioDeRosa** [comment]
PR updated. I double checked and everything works correctly. As soon as I get approval, I'll merge it.

**Comment by mgol** [comment]
LGTM

**Pull request closed without merging**
