### PR TITLE
isNumeric: Fixed a code style issue

### PR DESCRIPTION
**Pull request by AurelioDeRosa**

### CODE REVIEW

**Comment by arthurvr** [comment]
This is due to recent changes in the style guide and there are a bunch of other pages that still have this issue. So I'd prefer all fixes in one commit instead of fixing up page by page. I plan to work on doing it automated but haven't found the time yet.

**Comment by dmethvin** [comment]
Also, at jqsummit we were talking about the style guide and some of the recent changes that added things like spaces around function calls, particularly `) }` on its own line. So we may change it again, I wouldn't make any style changes until it settles.

**Comment by AurelioDeRosa** [comment]
Cool. Should I close it then?

**Comment by dmethvin** [comment]
Sure, we'll do a style sweep at some point. The code is still correct.

**Pull request closed without merging**
