### PR TITLE
Update jQuery.param.xml

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fix issue #636

### CODE REVIEW

**Comment by scottgonzalez** [comment]
This doesn't seem like a legit fix.

**Comment by AurelioDeRosa** [comment]
Why? If you refer to the fact that I removed the code is because all the other entries don't have code in the summary. Take as an example ":input Selector" and ":text Selector".

**Comment by scottgonzalez** [comment]
So there are other places that *should* use `<code>`. The bottom line is `<desc>` supports markup and the index page should be fixed.

**Comment by AurelioDeRosa** [comment]
Cool. That's exactly what I asked [here](https://github.com/jquery/api.jquery.com/issues/636#issuecomment-71497916).

**Comment by arthurvr** [comment]
> So there are other places that should use <code>. The bottom line is <desc> supports markup and the index page should be fixed.

@scottgonzalez Where should that be handled? Is it okay if I merge this in for now, and we open a separated issue for that?

**Comment by scottgonzalez** [comment]
I'd prefer if it were properly fixed, since our yet to be properly written style guide will say that the current content is correct.

**Comment by scottgonzalez** [comment]
With that being said, you can merge this if you want to.

**Comment by arthurvr** [comment]
Merged and deployed. Thanks for being that quick with opening a PR, @AurelioDeRosa.

**Pull request closed without merging**
