### PR TITLE
Fixes 659, Returning elements in DOM order is documented now

### LINKED ISSUE #659: Returning elements in DOM order is not documented
As of [jQuery 1.3.2](http://blog.jquery.com/2009/02/20/jquery-1-3-2-released/) elements are returned in DOM order (which is a useful feature). This is not documented anywhere that I could find on api.jquery.com though.

It is, however, documented on the [sizzle wiki](https://github.com/jquery/sizzle/wiki)

### PR DESCRIPTION
**Pull request by karan1276**

### CODE REVIEW

**Comment by arthurvr** [comment]
Hmm, I've never seen that CLA error before. @scottgonzalez might be able to tell us what's up?

**Comment by karan1276** [comment]
I made [pull requests to Globalize](https://github.com/jquery/globalize/pull/555) as well, everything went well there.
I also closed this pull request and made a new one but it still fails the test.
Hope this helps

**Comment by scottgonzalez** [comment]
This failed because the branch name has # in it, which causes the fetch to silently fail.

**Comment by scottgonzalez** [comment]
Specifically, what happens is that we run `git fetch https://github.com/karan1276/api.jquery.com.git #659-Returning-elements-in-DOM-order` which is effectively `git fetch https://github.com/karan1276/api.jquery.com.git` because the `#` starts a comment. Interestingly, GitHub command line instructions get this wrong too ;-)

**Comment by AurelioDeRosa** [comment]
Hi @karan1276. Can you [sign our CLA](http://contribute.jquery.org/CLA/) and edit your commit to match the email you'll use? Also, can you add a period between "in the array" and "most multi-element"?

**Comment by AurelioDeRosa** [comment]
Hi @karan1276. Are still interested in this PR?

**Comment by karan1276** [comment]
yes  @AurelioDeRosa, sorry to keep you waiting. I am thinking of dumping this PR all together  and submiting a new one. Too many things have gone wrong here. :smile:. i'll do that in a day or two.

**Comment by dmethvin** [comment]
I'm going to close this PR since its name is a problem. @karan1276 sorry about the technical snafu, please feel free to resubmit under a different name.

**Pull request closed without merging**
