### PR TITLE
Made == to ===

### PR DESCRIPTION
**Pull request by vihanb**
Made all the `==` into `===` in Types.html because `===` is almost always better and promotes better practice.

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
LGTM

**Comment by dmethvin** [comment]
LGTM too, just need the CLA to be signed.

**Comment by vihanb** [comment]
I've signed the CLA, and updated my Github name to match, is there anything else I need to do to make it update?

**Comment by AurelioDeRosa** [comment]
@dmethvin I think the reason why the label isn't updated is because there are still issues. Is that correct?

**Comment by arthurvr** [comment]
The author of the git commit doesn't contain your last name, I think that's the problem. There are instructions [here](http://contribute.jquery.org/CLA/status/?repo=api.jquery.com&sha=14b437cb3b91e2b2ecfcb3e8b8a19a27d6714c5e#updating-git-config) on how to fix it, just don't forget to fix the first commit too.

**Comment by AurelioDeRosa** [comment]
Hi @vihanb. Would you mind fixing your commit so that I can merge this PR?

**Comment by vihanb** [comment]
So the first commit is the one that doesn't seem to be updating the name. I've tried running `git rebase -i` and all that stuff but that didn't seem to fix it

**Comment by vihanb** [comment]
Oh okay, I've got it fixed

**Comment by AurelioDeRosa** [comment]
Great, thank you.

**Comment by AurelioDeRosa** [comment]
@jquery/content I need a small advice here. The user has created two commits with unrelated changes but both of them are good to merge. Should I ask the user to create a new PR out of the second commit? THe problem is that for the second I cannot use the usual Closes gh-XXX format.

**Comment by kswedberg** [comment]
@AurelioDeRosa, If both commits look good, I think you should go ahead and merge them. After you push the changes, you can go to the issue covered by the second commit and manually post a comment saying "Closed by [SHA]." (replacing [SHA] with the actual commit sha). Sound reasonable?

**Comment by AurelioDeRosa** [comment]
Unfortunately we don't have an issue open for that either. However, I can easily open one.

**Comment by kswedberg** [comment]
Ah, I see. Yeah, open an issue, please. And thank you!

**Pull request closed without merging**
