### PR TITLE
ajax: Specified that "?" in data is replaced

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-999

### CODE REVIEW

**Comment by dmethvin** [comment]
I think this is too broad a statement, see this http://jsbin.com/dicigovevo/edit?html,console and also #878 which is a bit of a dup. There's some lengthy discussion in https://bugs.jquery.com/ticket/8417 .

The essence of the problem is that when users send their own plain string (instead of an object) as `data` they must ensure that it is either formatted properly as form-url-encoded data or else specify a `contentType` that says how the data is encoded.  It is not possible for form-url-encoded data to contain `??` by the definition of the format. 

I kept trying to explain it all and I ended up with something like this, which is probably 3 paragraphs.

> Data to be sent to the server. If the HTTP method is one that cannot have an entity body, such as GET, the `data` is appended to the URL. When `data` is an object, jQuery generates the data string from the object's key/value pairs unless the `processData` option is set to `false`. For example, `{ a: "bc", d: "e,f" }` is converted to the string `"a=bc&d=e%2Cf"`. If the value is an array, jQuery serializes multiple values with same key based on the value of the `traditional` setting (described below). For example, `{ a: [1,2] }` becomes the string `"a%5B%5D=1&a%5B%5D=2"` with the default `traditional: false` setting. When `data` is passed as a string it should *already be encoded* using the correct encoding for `contentType`, which by default is `application/x-www-form-urlencoded`. If the string contains a double question mark (`??`) it is replaced with a value generated by jQuery that is unique for each copy of the library on the page (e.g. jQuery21406515378922229067_1479880736745).

**Comment by mgol** [comment]
@dmethvin it seems that your version is pretty different to the one in this PR. Could you report it as a PR? We'd be able to close this one then (I'm trying to clear up stale PRs).

**Comment by mgol** [comment]
@dmethvin ping

**Comment by AurelioDeRosa** [comment]
Agree with @mgol. @dmethvin's text is much more complete, so happy to close mine in favor of a PR fro him.

**Comment by mgol** [comment]
@dmethvin Ping about https://github.com/jquery/api.jquery.com/pull/1005#issuecomment-273006794

**Comment by mgol** [comment]
I submitted @dmethvin's text in #1171 so let's close this one.

**Pull request closed without merging**
