### PR TITLE
Submit-selector: Fix indentation for closing style tag

### PR DESCRIPTION
**Pull request by agcolom**

### CODE REVIEW

**Comment by arthurvr** [comment]
Yeah, I believe this is the right thing, but doesn't the rest of the indentation on that page need to be changed then too?

**Comment by agcolom** [comment]
I don't think so. Note that some of the indentation is taken care of by the xslt.

**Comment by agcolom** [comment]
@arthurvr what other indentation do you see needs changing?

**Comment by agcolom** [comment]
@arthurvr did you mean indent inside form?

**Comment by arthurvr** [comment]
@agcolom Whoops! Looks good indeed, I was looking at the code above in split view, and that screwed it up.

**Pull request closed without merging**
