### PR TITLE
jQuery.parseJSON: Added deprecation note for jQuery 3

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-898

### CODE REVIEW

**Comment by dmethvin** [comment]
:+1:

**Comment by AurelioDeRosa** [comment]
The PR has been merged in the branch v3.0.0-docs.

**Comment by mgol** [comment]
Now that I look at it... On other pages we put the deprecation message at the top so that it's immediately obvious not to use the API. I think we should move this one to the top as well.

**Comment by mgol** [comment]
@dmethvin @AurelioDeRosa PTAL at #1000.

**Pull request closed without merging**
