### PR TITLE
Typo in contents.xml

### PR DESCRIPTION
**Pull request by Fuhrmann**
Just a typo.

### CODE REVIEW

**Comment by arthurvr** [comment]
ping @Fuhrmann, about the above. The team can only land stuff if you signed the CLA.

**Comment by arthurvr** [comment]
Could somebody add the `needs CLA signature` label? It's made for that :)

**Comment by Fuhrmann** [comment]
Signed!

**Comment by arthurvr** [comment]
Seems like we didn't spot a duplicate PR, and https://github.com/jquery/api.jquery.com/commit/a3cc9b422c5c245a1f334f65de82275dda048084 landed.   Sorry, @Fuhrmann!

**Pull request closed without merging**
