### PR TITLE
Added page about the contextmenu() alias

### LINKED ISSUE #806: Documentation about contextmenu() is missing
The website doesn't have a documentation page for the `contextmenu()` alias which is supported since the early days of jQuery.

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes #806

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Anyone keen to review again the PR?

**Comment by arthurvr** [comment]
Would appreciate if someone from the core team could take a look too just to make sure we don't miss out on anything. cc @timmywil @dmethvin @markelog @gibson042

**Comment by markelog** [comment]
It is common perception in Core team, that event aliases are tricky shouldn't be used so they might be even deprecated in the future, also it looks like we don't have any tests for it  - https://github.com/jquery/jquery/issues/2636

**Comment by arthurvr** [comment]
Yeah, I know. I always prefer to avoid them too but still it's better to have them at least documented. Maybe we should add some kind of note that tells people to avoid these methods though.

**Comment by markelog** [comment]
> Maybe we should add some kind of note that tells people to avoid these methods though.

That sounds like deprecation notice :-)

**Comment by AurelioDeRosa** [comment]
Based on your comments, I'd say let's add the note *if* and *when* these shortcuts will be deprecated.

**Comment by AurelioDeRosa** [comment]
@kswedberg can you perform a final check please?

**Comment by kswedberg** [comment]
LGTM! :+1:

**Pull request closed without merging**
