### PR TITLE
Event: Suggest event.originalEvent usage

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/jquery/api.jquery.com/issues/405

cc: @mgol @dmethvin

### CODE REVIEW

**Comment by silverwind** [comment]
Tweaked slightly.

**Comment by mgol** [comment]
I like it!

**Comment by dmethvin** [comment]
Yes! That also works for any version which is good, rather than being 3.0-specific.

**Comment by mgol** [comment]
After 3.0 we'll need to add more props to the list but that may be done separately.

**Comment by mgol** [comment]
Landed, thanks @silverwind!

**Pull request closed without merging**
