### PR TITLE
jQuery.param: Removed details about traditional flag

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-919

### CODE REVIEW

**Comment by dmethvin** [comment]
LGTM, it just needs to be moved to the 3.0 branch and the existing wording is fine.

**Comment by AurelioDeRosa** [comment]
I was thinking that but because we forked it so long ago, in branch v3 we still have the text.

**Comment by dmethvin** [comment]
Oh true, although it still says 1.8 right?

**Comment by AurelioDeRosa** [comment]
Oh, true. I think I'm going to rebase the branch today because it's now very old. Once done that, I'm going to submit a PR to address it.

**Comment by AurelioDeRosa** [comment]
I've submitted PR #932 to address the last problem left with this PR, so it's now good to merge.

**Pull request closed without merging**
