### PR TITLE
Manipulation: fix after/before xml parsing

### PR DESCRIPTION
**Pull request by timmywil**
I ran `grunt deploy` locally and ran into this error. Not sure why it's not happening in CI testing. This update seems to fix it.

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
What operating system are you using? If it's Windows, I can try to replicate your issue. Also, what's the error?

**Comment by timmywil** [comment]
I'm using Mac 10.11.2. Error is...

```
Running "build-xml-entries:all" (build-xml-entries) task
>> Error: element a: validity error : ID after-function already defined
```

**Comment by AurelioDeRosa** [comment]
PR looks good to me, so I can merge. However, before doing it if anyone with a Mac could try it, we can understand the reason behind the error.

**Comment by timmywil** [comment]
I don't think there's a danger in merging. I'm surprised Windows users don't see this error. There are duplicate names.

**Pull request closed without merging**
