### PR TITLE
clarify documentation for outerWidth and outerHeight

### LINKED ISSUE #882: .outerWidth() and .outerHeight() don't specify the default values of the 'includeMargin' argument
All other function docs specify the default value for their optional parameters (e.g. `.animate()`: `duration (default: 400)`) , but `.outerWidth()` and `.outerHeight()` do not. As far as I'm aware the default value is `includeMargin: false` but I'd appreciate if someone could double-check this.

### PR DESCRIPTION
**Pull request by IanKemp**
Fixes #882.

### CODE REVIEW

**Comment by IanKemp** [comment]
I signed the CLA, plzkthx.

**Comment by AurelioDeRosa** [comment]
The PR looks good to me but it seems there are still problems with the CLA.

**Comment by IanKemp** [comment]
I don't know what's up with the CLA. I signed it but the "check CLA status" link doesn't work.

**Comment by agcolom** [comment]
@IanKemp the issue with the CLA is that there is a mismatch with your email address. You signed the CLA with your gmail address, but the PR is associated with another email address, see https://patch-diff.githubusercontent.com/raw/jquery/api.jquery.com/pull/883.patch 
If you sign again with your name and that email address, it'll be all green :-) thanks :-)

**Comment by IanKemp** [comment]
Ugh, my repo was setup with my work email address instead of my personal. Signed the CLA with the former, seems fine now, sorry for the trouble.

**Comment by agcolom** [comment]
@IanKemp No worries at all and thanks very much for signing again and the PRs :-)

**Comment by AurelioDeRosa** [comment]
Merged. Thank you @IanKemp.

**Pull request closed without merging**
