### PR TITLE
Completed the list of copied props of jQuery.Event.

### PR DESCRIPTION
**Pull request by andyli**
Source ref: https://github.com/jquery/jquery/blob/master/src/event.js (props, keyHooks.props, mouseHooks.props)

### CODE REVIEW

**Comment by dmethvin** [comment]
This LGTM. It's adding the standard mouse and key events to the "also copied" list but since we say they can be `undefined` that covers the case for things like mouse properties on a key event well enough.  Thanks @andyli!

**Comment by AurelioDeRosa** [comment]
It looks good to me as well, thank you @andyli. Should I merge it?

**Comment by kswedberg** [comment]
@AurelioDeRosa , yes, please merge away! :+1:

**Comment by arthurvr** [comment]
:+1: Thanks!

**Pull request closed without merging**
