### PR TITLE
Selector: correct `removed` version number

### PR DESCRIPTION
**Pull request by arthurvr**
Fixes gh-696

### CODE REVIEW

**Comment by arthurvr** [comment]
@AurelioDeRosa @dmethvin WDYT?

**Comment by AurelioDeRosa** [comment]
I think this PR is fine but it should be changed for context as well.

**Comment by arthurvr** [comment]
Sure thing. Updated that.

**Comment by AurelioDeRosa** [comment]
Thank you for the change @arthurvr. This PR is now good to be merged.

**Comment by arthurvr** [comment]
Merged in v3 branch.

**Pull request closed without merging**
