### PR TITLE
Visible: Specified new behavior

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-737

### CODE REVIEW

**Comment by arthurvr** [comment]
This also affects `:hidden` so let's also add a note on that entry.

**Comment by AurelioDeRosa** [comment]
You didn't give me the time :)

PR updated.

**Comment by AurelioDeRosa** [comment]
Merged with commit d0e7282d4c0e9c02263ebcb15ecd419a25113941.

**Comment by mzgol** [comment]
Why "will be"? Isn't this supposed to go live when jQuery 3 is released when the future tense won't make sense?

**Comment by arthurvr** [comment]
@AurelioDeRosa We all open PRs and wait for code reviews before landing something and I'd prefer if you did so too. That's the point of PRs :)

**Comment by AurelioDeRosa** [comment]
You saw this PR after ~30 seconds it was made and the only comment you had was

> This also affects :hidden so let's also add a note on that entry.

I took it as a LGTM. Simple as that, there is no need to paternalize. :)

**Comment by arthurvr** [comment]
> you saw this PR after ~30 seconds it was made and the only comment you had was

Yes, because I'm not going to review a PR when it's not complete yet. Just like everybody does, please wait for an LGTM, :+1: or alike comment.

**Comment by arthurvr** [comment]
And for https://github.com/jquery/api.jquery.com/pull/779, you didn't have any comment yet ;)

**Pull request closed without merging**
