### PR TITLE
README: fix link for getting xmllint and xsltproc

### LINKED ISSUE #668: Replace GnuWin32 link
A while ago a user reported us an issue (#71) that caused the build to fail on Windows. @kswedberg fixed the documentation by updating the link with commit 6559302856cf3fecefa319d3d7ce1877c694b41b. The link was then changed again by @scottgonzalez with commit 04f42c47bfa8a3236b76dd69a332359384a1a4b5. However, I had the same issue of the user and ended up using the files at http://www.zlatkovic.com/libxml.en.html.

So, do you agree that we should replace the GnuWin32 link?

### PR DESCRIPTION
**Pull request by arthurvr**
Would fix #668. Once this one gets merged, I will submit a PR to every API repo.

### CODE REVIEW

**Comment by arthurvr** [comment]
@scottgonzalez It would be nice if you could give this a +1 when it looks good. I'm not that familiar with our whole build system so would like another pair of eyes on it.

**Comment by scottgonzalez** [comment]
I'm +1 based on other peoples' feedback. I don't use Windows, so I can't provide any actual feedback.

#669 would need to go into all repos as well.

**Comment by arthurvr** [comment]
> I'm +1 based on other peoples' feedback

@AurelioDeRosa This worked for you right?

**Comment by arthurvr** [comment]
> #669 would need to go into all repos as well.

I'll do that on the while.

**Comment by AurelioDeRosa** [comment]
I had to download those files plus add the DLL as per #669 @arthurvr.

**Pull request closed without merging**
