### PR TITLE
val(): Updated description for the setter version

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes: gh-712

### CODE REVIEW

**Comment by gibson042** [comment]
> the <code>option</code> whose value appears last in the array will be selected.

I'm not sure we want to lock ourselves into that behavior. It's not terribly likely to change, but it's also not a great idea to pass in junk and let us sort it out. I'd rather not dignify (or encourage) it with recognition.

**Comment by AurelioDeRosa** [comment]
Thank you for the feedback @gibson042. Anyone wants to comment before I update the PR?

**Comment by AurelioDeRosa** [comment]
PR updated.

**Comment by AurelioDeRosa** [comment]
Anyone keen to review this PR?

**Comment by gnarf** [comment]
One question I have about this behavior after reading the changed text:

* Will `$( "input.checkboxes" ).val( anArrayOfValues )` set `elem.checked = false` if the value is not in the array as well?

**Comment by AurelioDeRosa** [comment]
@gnarf Yes, it does. I'll update the PR accordingly.

**Comment by AurelioDeRosa** [comment]
Can you double check this PR @arthurvr?

**Pull request closed without merging**
