### PR TITLE
Update jQuery.getJSON.xml

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
`data` can be a string too

### CODE REVIEW

**Comment by arthurvr** [comment]
This changes LGTM.

**Comment by AurelioDeRosa** [comment]
Friendly ping :)

**Comment by dmethvin** [comment]
@AurelioDeRosa it looks good to me but i don't have a working docs setup right now so I prefer not to land it ... just in case there is some XML issue or other problem. @kswedberg can you land this?

**Comment by kswedberg** [comment]
Sure thing, @dmethvin .

**Comment by kswedberg** [comment]
Closed by a6b3b6ffcb6e6366fd1dfc92d43950f74647a987

**Pull request closed without merging**
